[project]
name = "course-tdd-celery-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.1",
    "fastapi[standard]>=0.115.12",
    "redis>=5.2.1",
]
