#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

alembic upgrade head

if [[ "${DEBUG:-0}" == "1" ]]; then
  echo "🚩 Running in DEBUG mode with debugpy attached on port 5678"
  python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --reload-dir project --host 0.0.0.0
else
  uvicorn main:app --reload --reload-dir project --host 0.0.0.0
fi